src/Entity/UserDetails.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserDetailsRepository")
 */
class UserDetails
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/UserDetails1Type.php
<?php

namespace App\Form;

use App\Entity\UserDetails;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserDetails1Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('first_name')
            ->add('last_name')
            ->add('gender')
            ->add('password')
            ->add('status')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => UserDetails::class,
        ]);
    }
}

src/Form/UserDetailsType.php
<?php

namespace App\Form;

use App\Entity\UserDetails;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserDetailsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user_id')
            ->add('username')
            ->add('first_name')
            ->add('last_name')
            ->add('gender')
            ->add('password')
            ->add('status')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => UserDetails::class,
        ]);
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Repository\UserDetailsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    private $columns;

    public function __construct()
    {
        $this->columns = ["id", "username", "first_name", "last_name", "gender", "password", "status"];
    }

    /**
     * @Route("/", name="homepage")
     */
    public function index(): Response
    {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
            'columns' => $this->columns,
        ]);
    }

    /**
     * @Route("/ajax/data", name="users", methods={"POST"})
     */
    public function users(UserDetailsRepository $userDetailsRepository, Request $request): JsonResponse
    {
        $column = $this->columns[$request->request->get('order')[0]['column']];

        $userDetailsRepository->select(
            $request->request->get('start'),
            $request->request->get('length'),
            $column,
            $request->request->get('order')[0]['dir'],
            $request->request->get('search')['value']
        );

        $json = new \stdClass();
        $json->draw = $request->request->get('draw');
        $json->recordsTotal = $userDetailsRepository->total();
        $json->recordsFiltered = $userDetailsRepository->totalFiltered();
        $json->data = $userDetailsRepository->arrayResults();

        return new JsonResponse($json, 200);
    }
}

src/Controller/UserDetailsController.php
<?php

namespace App\Controller;

use App\Entity\UserDetails;
use App\Form\UserDetails1Type;
use App\Repository\UserDetailsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user/details")
 */
class UserDetailsController extends AbstractController
{
    /**
     * @Route("/", name="user_details_index", methods={"GET"})
     */
    public function index(UserDetailsRepository $userDetailsRepository): Response
    {
        return $this->render('user_details/index.html.twig', [
            'user_details' => $userDetailsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_details_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $userDetail = new UserDetails();
        $form = $this->createForm(UserDetails1Type::class, $userDetail);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($userDetail);
            $entityManager->flush();

            return $this->redirectToRoute('user_details_index');
        }

        return $this->render('user_details/new.html.twig', [
            'user_detail' => $userDetail,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_details_show", methods={"GET"})
     */
    public function show(UserDetails $userDetail): Response
    {
        return $this->render('user_details/show.html.twig', [
            'user_detail' => $userDetail,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_details_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, UserDetails $userDetail): Response
    {
        $form = $this->createForm(UserDetails1Type::class, $userDetail);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_details_index', [
                'id' => $userDetail->getId(),
            ]);
        }

        return $this->render('user_details/edit.html.twig', [
            'user_detail' => $userDetail,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_details_delete", methods={"DELETE"})
     */
    public function delete(Request $request, UserDetails $userDetail): Response
    {
        if ($this->isCsrfTokenValid('delete'.$userDetail->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($userDetail);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_details_index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous">
        <link rel="stylesheet" type="text/css"
              href="https://cdn.datatables.net/v/bs4/jq-3.3.1/dt-1.10.18/af-2.3.3/b-1.5.6/r-2.2.2/datatables.min.css"/>
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ path("homepage") }}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ path("user_details_index") }}">Crud <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

{% block body %}{% endblock %}
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script type="text/javascript"
            src="https://cdn.datatables.net/v/bs4/jq-3.3.1/dt-1.10.18/af-2.3.3/b-1.5.6/r-2.2.2/datatables.min.js"></script>
    <script type="text/javascript"
            src="https://cdn.datatables.net/scroller/2.0.0/js/dataTables.scroller.min.js"></script>
{% endblock %}
</body>
</html>

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <div class="container">
        <h1>Hello {{ controller_name }}! ✅</h1>

        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                {% for column in columns %}
                    <th>{{ column|humanize }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tfoot>
            <tr>
                {% for column in columns %}
                    <th>{{ column|humanize }}</th>
                {% endfor %}
            </tr>
            </tfoot>
        </table>

    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script>
        {#$(document).ready(function () {#}
            {#$('#example').DataTable({#}
                {#serverSide: true,#}
                {#sPaginationType: "scrolling",#}
                {#ajax: {#}
                    {#url: "{{ path("users") }}",#}
                    {#type: "POST"#}
                {#},#}
                {#columns: [#}
                    {#{% for column in columns %}#}
                    {#{"data": "{{ column }}"}{{ loop.last? "":"," }}#}
                    {#{% endfor %}#}
                {#]#}
            {#});#}
        {#});#}

        $(document).ready(function () {
            $('#example').DataTable({
                serverSide: true,
                ordering: true,
                searching: true,
                ajax: {
                    url: "{{ path("users") }}",
                    type: "POST"
                },
                columns: [
                    {% for column in columns %}
                    {"data": "{{ column }}"}{{ loop.last? "":"," }}
                    {% endfor %}
                ],
                scrollY: 600,
                scroller: {
                    loadingIndicator: true
                },
            });
        });
    </script>

{% endblock %}

templates/user_details/_delete_form.html.twig
<form method="post" action="{{ path('user_details_delete', {'id': user_detail.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user_detail.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user_details/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user_details/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit UserDetails{% endblock %}

{% block body %}
    <h1>Edit UserDetails</h1>

    {{ include('user_details/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_details_index') }}">back to list</a>

    {{ include('user_details/_delete_form.html.twig') }}
{% endblock %}

templates/user_details/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UserDetails index{% endblock %}

{% block body %}
    <h1>UserDetails index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>Gender</th>
                <th>Password</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user_detail in user_details %}
            <tr>
                <td>{{ user_detail.id }}</td>
                <td>{{ user_detail.username }}</td>
                <td>{{ user_detail.firstName }}</td>
                <td>{{ user_detail.lastName }}</td>
                <td>{{ user_detail.gender }}</td>
                <td>{{ user_detail.password }}</td>
                <td>{{ user_detail.status ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('user_details_show', {'id': user_detail.id}) }}">show</a>
                    <a href="{{ path('user_details_edit', {'id': user_detail.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_details_new') }}">Create new</a>
{% endblock %}

templates/user_details/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New UserDetails{% endblock %}

{% block body %}
    <h1>Create new UserDetails</h1>

    {{ include('user_details/_form.html.twig') }}

    <a href="{{ path('user_details_index') }}">back to list</a>
{% endblock %}

templates/user_details/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UserDetails{% endblock %}

{% block body %}
    <h1>UserDetails</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user_detail.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user_detail.username }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ user_detail.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ user_detail.lastName }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ user_detail.gender }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user_detail.password }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ user_detail.status ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_details_index') }}">back to list</a>

    <a href="{{ path('user_details_edit', {'id': user_detail.id}) }}">edit</a>

    {{ include('user_details/_delete_form.html.twig') }}
{% endblock %}